/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * AI Resume Analysis API
 * Backend API for AI-powered resume analysis. Matches CVs against job descriptions, identifies missing keywords, calculates compatibility scores, and generates personalized cover letter suggestions. Built with Node.js/Express.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Available activity types in the system
 */
export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityType = {
  RESUME_UPLOADED: "RESUME_UPLOADED",
  RESUME_DELETED: "RESUME_DELETED",
  JOB_MATCHED: "JOB_MATCHED",
  JOB_APPLIED: "JOB_APPLIED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
} as const;
