/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * AI Resume Analysis API
 * Backend API for AI-powered resume analysis. Matches CVs against job descriptions, identifies missing keywords, calculates compatibility scores, and generates personalized cover letter suggestions. Built with Node.js/Express.
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityType } from "./activityType";
import type { ActivityLogMetadata } from "./activityLogMetadata";

export interface ActivityLog {
  /** Unique identifier for the activity log */
  id: string;
  /** ID of the entity this activity relates to */
  entityId: string;
  /** Type of entity (resume, job, profile) */
  entityType: string;
  /** Human-readable activity message */
  message: string;
  type: ActivityType;
  /** Timestamp when activity occurred */
  createdAt: string;
  /**
   * Additional data stored as JSON
   * @nullable
   */
  metadata?: ActivityLogMetadata;
  /** Profile this activity belongs to */
  profileId: string;
}
