/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * AI Resume Analysis API
 * Backend API for AI-powered resume analysis. Matches CVs against job descriptions, identifies missing keywords, calculates compatibility scores, and generates personalized cover letter suggestions. Built with Node.js/Express.
 * OpenAPI spec version: 1.0.0
 */

export type GetInsightsImprovementInsights200 = {
  /** The average match score across all analyses */
  overallScore?: number;
  /** Percentage improvement compared to previous analyses */
  Improvement?: number;
};
