/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * AI Resume Analysis API
 * Backend API for AI-powered resume analysis. Matches CVs against job descriptions, identifies missing keywords, calculates compatibility scores, and generates personalized cover letter suggestions. Built with Node.js/Express.
 * OpenAPI spec version: 1.0.0
 */

export type PostAnalysisAnalyzeBody = {
  /** Title of the job position */
  jobTitle?: string;
  /** Company name for the job position */
  company?: string;
  /** The full job description text used for resume analysis */
  jobDescription: string;
  /** The unique ID of the resume to analyze */
  resumeId: string;
};
