/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * AI Resume Analysis API
 * Backend API for AI-powered resume analysis. Matches CVs against job descriptions, identifies missing keywords, calculates compatibility scores, and generates personalized cover letter suggestions. Built with Node.js/Express.
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthSignup201User } from "./postAuthSignup201User";
import type { PostAuthSignup201Session } from "./postAuthSignup201Session";

export type PostAuthSignup201 = {
  message?: string;
  user?: PostAuthSignup201User;
  session?: PostAuthSignup201Session;
  access_token?: string;
  refresh_token?: string;
};
