/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * AI Resume Analysis API
 * Backend API for AI-powered resume analysis. Matches CVs against job descriptions, identifies missing keywords, calculates compatibility scores, and generates personalized cover letter suggestions. Built with Node.js/Express.
 * OpenAPI spec version: 1.0.0
 */

export interface Resume {
  id?: string;
  storageKey?: string;
  profileId?: string;
  name?: string;
  status?: 'pending' | 'processing' | 'processed' | 'failed';
  fileUrl?: string;
  fileSize?: number;
  version?: number;
  isActive?: boolean;
  createdAt?: string;
}
