/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * AI Resume Analysis API
 * Backend API for AI-powered resume analysis. Matches CVs against job descriptions, identifies missing keywords, calculates compatibility scores, and generates personalized cover letter suggestions. Built with Node.js/Express.
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRefresh200User } from "./postAuthRefresh200User";

export type PostAuthRefresh200 = {
  message?: string;
  user?: PostAuthRefresh200User;
  access_token?: string;
};
