/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * AI Resume Analysis API
 * Backend API for AI-powered resume analysis. Matches CVs against job descriptions, identifies missing keywords, calculates compatibility scores, and generates personalized cover letter suggestions. Built with Node.js/Express.
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthSignup200User } from "./postAuthSignup200User";

export type PostAuthSignup200 = {
  message?: string;
  user?: PostAuthSignup200User;
  requiresEmailConfirmation?: boolean;
};
